openapi: 3.0.0
info:
  title: Coupang Recommend API
  version: 1.0.0
servers:
  - url: https://coupang-api.onrender.com
paths:
  /recommend:
    get:
      summary: 쿠팡 딥링크 생성기
      description: 사용자가 입력한 키워드로 쿠팡 검색 URL을 만들고, 짧은 딥링크로 반환합니다.
      parameters:
        - name: keyword
          in: query
          required: true
          schema:
            type: string
          description: 쿠팡에서 검색할 키워드 (예: 무선 이어폰)
      responses:
        '200':
          description: 딥링크 생성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  keyword:
                    type: string
                    description: 검색한 키워드
                  link:
                    type: string
                    description: 생성된 쿠팡 짧은 URL
        '500':
          description: 링크 생성 실패
