openapi: 3.1.0
info:
  title: Coupang Product Recommender API
  version: 2.0.0
  description: GPT가 추천한 제품 리스트를 받아 쿠팡 제휴 링크를 반환합니다.
servers:
  - url: https://coupang-api.onrender.com
paths:
  /recommend:
    post:
      operationId: getCoupangLinks
      summary: GPT 추천 제품으로 쿠팡 딥링크 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
                products:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                      summary:
                        type: string
                      review:
                        type: string
                      price:
                        type: string
                      image:
                        type: string
                      pros:
                        type: string
                      cons:
                        type: string
                      reason:
                        type: string
      responses:
        '200':
          description: 딥링크 포함 제품 목록 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  keyword:
                    type: string
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        summary:
                          type: string
                        review:
                          type: string
                        price:
                          type: string
                        image:
                          type: string
                        pros:
                          type: string
                        cons:
                          type: string
                        reason:
                          type: string
                        link:
                          type: string
                  searchLink:
                    type: string
